# Generated by Django 4.2.6 on 2023-10-24 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bl',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nro_bl', models.CharField(max_length=255)),
                ('puerto_de_carga', models.CharField(max_length=255)),
                ('puerto_de_descarga', models.CharField(max_length=255)),
                ('vessel', models.CharField(max_length=255)),
                ('peso', models.CharField(max_length=255)),
                ('nro_voyage', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'bl',
                'managed': False,
            },
        ),
    ]
